### ISSUE TITLE
Remove has_a_best_boy class method

### ISSUE THREAD

**Issue by carpodaster** [Absolventa/best_boy#11]
Only use modules:

    include BestBoy::Model
    # Or to modularize it further:
    include BestBoy::Model::Associations
    include BestBoy::Model::Callbacks#

**Comment by cseydel** [comment]
Noooooooooooooo
> Am 15.06.2015 um 17:00 schrieb Daniel Schoppmann <notifications@github.com>:
> 
> Closed #11 <https://github.com/Absolventa/best_boy/issues/11> via #19 <https://github.com/Absolventa/best_boy/pull/19>.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/Absolventa/best_boy/issues/11#event-331124622>.
> 

---
Christoph Seydel
Dipl.-Inf. (FH)

Moselstr. 23
66333 Völklingen

T:	+49 (0)6898 4982689
F:	+49 (0)6898 49826899
M:	+49 (0)151 12441861

Web: www.christophseydel.pro <http://www.christophseydel.pro/>
Xing: www.xing.com/profile/Christoph_Seydel2 <http://hwww.xing.com/profile/Christoph_Seydel2>
LinkedIn: www.linkedin.com/pub/christoph-seydel/42/462/b05 <http://www.linkedin.com/pub/christoph-seydel/42/462/b05>

**Comment by carpodaster** [comment]
![Noooooooo](https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.fightersgeneration.com%2Fcharacters4%2Fvader-nooooo.jpg&f=1)
