### ISSUE TITLE
Trigger event creation via after_commit hook instead of after_create/after_destroy

### ISSUE THREAD

**Issue by neumanrq** [Absolventa/best_boy#20]
Currently the events of an `BestBoy::Eventable` will be created via `after_create` and `after_destroy` callbacks. 

The problem here is that, e.g. `after_create` is invoked _before_ the corresponding database transaction is terminated. That implies that a `BestBoy::Event` for `create` is created although the underlying resource has not been persisted sucessfully.

Let's use `after_commit` instead to prevent this.

**Comment by carpodaster** [comment]
This is the fella you mentioned in today's standup, right? Do you have a temporary branch?

**Comment by neumanrq** [comment]
Yup, here's the [branch](https://github.com/Absolventa/best_boy/tree/fix/create_events_in_after_commit_hooks)

Specs are stopping locally with Rails 5 (using appraisals) with this message:
```Ruby
rake aborted!
ActiveRecord::NoEnvironmentInSchemaError:

Environment data not found in the schema. To resolve this issue, run:

        bin/rails db:environment:set RAILS_ENV=development

/Users/robin/.rvm/gems/ruby-2.3.0@best_boy/gems/activerecord-5.0.0.beta4/lib/active_record/migration.rb:1259:in `last_stored_environment'
/Users/robin/.rvm/gems/ruby-2.3.0@best_boy/gems/activerecord-5.0.0.beta4/lib/active_record/tasks/database_tasks.rb:48:in `check_protected_environments!'
/Users/robin/.rvm/gems/ruby-2.3.0@best_boy/gems/activerecord-5.0.0.beta4/lib/active_record/railties/databases.rake:11:in `block (2 levels) in <top (required)>'
/Users/robin/.rvm/gems/ruby-2.3.0@best_boy/gems/activerecord-5.0.0.beta4/lib/active_record/railties/databases.rake:375:in `block (3 levels) in <top (required)>'
/Users/robin/.rvm/gems/ruby-2.3.0@best_boy/bin/ruby_executable_hooks:15:in `eval'
/Users/robin/.rvm/gems/ruby-2.3.0@best_boy/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => app:db:test:load => app:db:test:purge => app:db:check_protected_environments
```

The discussion on a [recent rails issue](https://github.com/rails/rails/issues/23279) looks related, but I can't extract a concrete consequence we could apply to fix right now.

The last rails version I tried was `5.0.0.beta4`.
